const GET_ALL_NAVLIST = 'navigation_list/GET_ALL';

const FETCH_START_GET_NAVIGATION_LIST =
  'navigation_list/FETCH_START_GET_NAVIGATION_LIST';

const TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU =
  'navigation_list/TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU';

const SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE =
  'navigation_list/SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE';

const ERROR_WHILE_FETCHING_NAVLIST =
  'navigation_list/ERROR_WHILE_FETCHING_NAVLIST';

const FETCH_START_CAROUSEL_IMAGES_LIST =
  'carousel/FETCH_START_CAROUSEL_IMAGES_LIST';

const FETCH_SUCCESS_CAROUSEL_IMAGES_LIST =
  'carousel/FETCH_SUCCESS_CAROUSEL_IMAGES_LIST';

const FETCH_ERROR_CAROUSEL_IMAGES_LIST =
  'carousel/FETCH_ERROR_CAROUSEL_IMAGES_LIST';

export default {
  GET_ALL_NAVLIST,
  TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU,
  SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE,
  ERROR_WHILE_FETCHING_NAVLIST,
  FETCH_START_CAROUSEL_IMAGES_LIST,
  FETCH_SUCCESS_CAROUSEL_IMAGES_LIST,
  FETCH_ERROR_CAROUSEL_IMAGES_LIST,
  FETCH_START_GET_NAVIGATION_LIST,
};
