const GET_ALL_NAVLIST = 'navigation_list/GET_ALL';

const TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU =
  'navigation_list/TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU';

export default { GET_ALL_NAVLIST, TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU };
