const GET_ALL_NAVLIST = 'navigation_list/GET_ALL';

const TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU =
  'navigation_list/TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU';

const SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE =
  'navigation_list/SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE';

export default {
  GET_ALL_NAVLIST,
  TOGGLE_NAVLIST_ITEM_IS_OPEN_SUBMENU,
  SET_ALL_NAVLIST_ITEM_IS_OPEN_SUBMENU_TO_FALSE,
};
