const FETCH_START = '[news]/FETCH_START';

const FETCH_SUCCESS_ACTUAL_NEWS = '[news]/FETCH_SUCCESS_ACTUAL_NEWS';

const FETCH_SUCCESS_ACTUAL_NEWS_ITEM_BY_ID =
  '[news]/FETCH_SUCCESS_ACTUAL_NEWS_ITEM_BY_ID';

const FETCH_ERROR_ACTUAL_NEWS = '[news]/FETCH_ERROR_ACTUAL_NEWS';

export default {
  FETCH_START,
  FETCH_SUCCESS_ACTUAL_NEWS,
  FETCH_SUCCESS_ACTUAL_NEWS_ITEM_BY_ID,
  FETCH_ERROR_ACTUAL_NEWS,
};
